
TrajectoryPlannerROS:
    max_vel_x: 0.2
    min_vel_x: 0.05
    max_vel_theta: 0.35
    min_vel_theta: -0.35
    min_in_place_vel_theta: 0.25

    acc_lim_theta: 0.25
    acc_lim_x: 2.5
    acc_lim_y: 2.5

    holonomic_robot: false
    
    meter_scoring: true # defines if cost function args are expressed in map cells or meters (true -> meters are considered)
    
    xy_goal_tolerance: 0.15
    yaw_goal_tolerance: 0.25
