
TrajectoryPlannerROS:
    max_vel_x: 0.74
    min_vel_x: 0.001
    max_vel_theta: 0.005
    min_in_place_vel_theta: 0.005

    acc_lim_theta: 0.1
    acc_lim_x: 0.4
    acc_lim_y: 0.4

    holonomic_robot: false