# Obstacle range: determines the maximum range sensor reading that will result in an obstacle being put into the costmap
obstacle_range: 0.35


#The "raytrace_range" parameter determines the range to which we will raytrace freespace
#given a sensor reading. Setting it to x meters as we have above means that the robot will
#attempt to clear out space in front of it up to x meters away given a sensor reading.

raytrace_range: 0.1


footprint: [[-0.09, -0.1385], [-0.09, 0.0415], [0.09, 0.0415], [0.09, -0.1385]]


# The inflation radius should be set to the maximum distance from obstacles at which a
#cost should be incurred. For example, setting the inflation radius at x meters means
#that the robot will treat all paths that stay x meters or more away from obstacles as
#having equal obstacle cost.

inflation_radius: 0.04

observation_sources: front_point_cloud_sensor
point_cloud_sensor: {sensor_frame: ultrasonic_front_emission_point, data_type: PointCloud, topic: front_point_cloud_data, marking: true, clearing: true}

observation_sources: back_point_cloud_sensor
point_cloud_sensor: {sensor_frame: ultrasonic_back_emission_point, data_type: PointCloud, topic: back_point_cloud_data, marking: true, clearing: true}

observation_sources: left_point_cloud_sensor
point_cloud_sensor: {sensor_frame: ultrasonic_left_emission_point, data_type: PointCloud, topic: left_point_cloud_data, marking: true, clearing: true}

observation_sources: right_point_cloud_sensor
point_cloud_sensor: {sensor_frame: ultrasonic_right_emission_point, data_type: PointCloud, topic: right_point_cloud_data, marking: true, clearing: true}