global_costmap:
    global_frame: /map
    robot_base_frame: base_link
    update_frequency: 1.0
    static_map: true
    publish_frequency: 0.5
    transform_tolerance: 0.5

#link: http://wiki.ros.org/navigation/Tutorials/RobotSetup
