local_costmap:
    global_frame: map
    robot_base_frame: base_link
    update_frequency: 3.0
    publish_frequency: 2.0
    static_map: false
    rolling_window: true
    width: 1.0
    height: 1.0
    origin_x: -0.5
    origin_y: -0.5
    resolution: 0.5
    transform_tolerance: 2.0
