local_costmap:
    global_frame: map
    robot_base_frame: base_link
    update_frequency: 5.0
    publish_frequency: 5.0
    static_map: false
    rolling_window: true
    width: 0.3
    height: 0.3
    resolution: 0.02
