local_costmap:
    global_frame: odom
    robot_base_frame: base_link
    update_frequency: 3.0
    publish_frequency: 2.0
    static_map: false
    rolling_window: true
    width: 0.4
    height: 0.4
    resolution: 0.03
    transform_tolerance: 2.0
